version: '2'
services:
  zoo1:
    image: zookeeper # 配置
    restart: always # 重启
    container_name: zoo1
    hostname: zoo1
    ports:
      - "2181:2181"
    volumes:
      - "./zookeeper/zooConfig/zoo.cfg:/conf/zoo.cfg" # 配置
      - "/opt/module/mq/zookeeper/zookeeper1/data:/data"
      - "/opt/module/mq/zookeeper/zookeeper1/datalog:/datalog"
    environment:
      ZOO_MY_ID: 1 # id
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.23.0.11
  zoo2:
    image: zookeeper # 配置
    restart: always # 重启
    container_name: zoo2
    hostname: zoo2
    ports:
      - "2182:2181"
    volumes:
      - "./zookeeper/zooConfig/zoo.cfg:/conf/zoo.cfg" # 配置
      - "/opt/module/mq/zookeeper/zookeeper2/data:/data"
      - "/opt/module/mq/zookeeper/zookeeper2/datalog:/datalog"
    environment:
      ZOO_MY_ID: 2 # id
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.23.0.12
  zoo3:
    image: zookeeper # 配置
    restart: always # 重启
    container_name: zoo3
    hostname: zoo3
    ports:
      - "2183:2181"
    volumes:
      - "./zookeeper/zooConfig/zoo.cfg:/conf/zoo.cfg" # 配置
      - "/opt/module/mq/zookeeper/zookeeper3/data:/data"
      - "/opt/module/mq/zookeeper/zookeeper3/datalog:/datalog"
    environment:
      ZOO_MY_ID: 3 # id
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      default:
        ipv4_address: 172.23.0.13
  kafka1:
    image: wurstmeister/kafka # 镜像
    restart: always
    container_name: kafka1
    hostname: kafka1
    ports:
      - 9092:9092
      - 9999:9999
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.159.132:9092 # 暴露在外的地址
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_PORT: 9092 # 暴露在外的端口
      KAFKA_BROKER_ID: 0
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      JMX_PORT: 9999 # jmx
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/opt/module/mq/kafka/kafka1/logs:/kafka"
    links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.23.0.14
  kafka2:
    image: wurstmeister/kafka # 镜像
    restart: always
    container_name: kafka2
    hostname: kafka2
    ports:
      - 9093:9092
      - 9998:9999
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.159.132:9093 # 暴露在外的地址
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_PORT: 9093 # 暴露在外的端口
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      JMX_PORT: 9999 # jmx
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/opt/module/mq/kafka/kafka2/logs:/kafka"
    links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.23.0.15
  kafka3:
    image: wurstmeister/kafka # 镜像
    restart: always
    container_name: kafka3
    hostname: kafka3
    ports:
      - 9094:9092
      - 9997:9999
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.159.132:9094 # 暴露在外的地址
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_HOST_NAME: kafka3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_ADVERTISED_PORT: 9094 # 暴露在外的端口
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      JMX_PORT: 9999 # jmx
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/opt/module/mq/kafka/kafka3/logs:/kafka"
    links:
      - zoo1
      - zoo2
      - zoo3
    networks:
      default:
        ipv4_address: 172.23.0.16
  kafka-manager:
    image: hlebalbau/kafka-manager
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - 9000:9000
    links:
      - kafka1
      - kafka2
      - kafka3
      - zoo1
      - zoo2
      - zoo3
    environment:
      ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKERS: kafka1:9092,kafka2:9092,kafka3:9092
      APPLICATION_SECRET: letmein
      KAFKA_MANAGER_AUTH_ENABLED: "true" # 开启验证
      KAFKA_MANAGER_USERNAME: "admin" # 用户名
      KAFKA_MANAGER_PASSWORD: "admin" # 密码
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      default:
        ipv4_address: 172.23.0.10
networks:
  default:
    external:
      name: zookeeper_network