server:
  port: 8082
  context-path: /shuai8082
logging:
  level:
    org:
      springframework:
        messaging: info
        web:
          socket: info
commons:
  websocket:
    heart-beat-interval: 15000
spring:
  redis:
    host: 192.168.220.128
    port: 6379
    password: 123456