server:
  port: 8082
logging:
  level:
    org:
      springframework:
        messaging: debug
        web:
          socket: info
commons:
  websocket:
    heart-beat-interval: 10000
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
