server:
  port: 8082
logging:
  level:
    org:
      springframework:
        messaging: info
        web:
          socket: info
commons:
  websocket:
    heart-beat-interval: 10000
virtual-host:
  centos: 192.168.220.128
spring:
  redis:
    host: ${virtual-host.centos}
    port: 6380
    password: 123456
    sentinel:
      master: mymaster
      nodes: ${virtual-host.centos}:26380,${virtual-host.centos}:26381,${virtual-host.centos}:26382