server:
  port: 8081

kem:
  websocket:
    server:
      #connectUri: ws://localhost/kircp-servers/kircp/ws/stomp
      #connectUri: ws://localhost:8092/kircp/ws/stomp
      #connectUri: ws://192.168.159.132/ws/stomp
      connectUri: ws://192.168.8.34/kircp-server/kircp/ws/stomp