spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/daishuai?useSSL=false&amp;characterEncoding=utf-8&amp;serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: c##keda
#    password: root
#    url: jdbc:oracle:thin:@localhost:1521/ORCL
