spring:
  elasticsearch:
    default-cluster: dev
    clusters:
      default:
        rest-nodes: 10.148.191.57:39200
        thread-num: 10
        sniff: false
      dev:
        rest-nodes: http://localhost
        path-prefix: /es-common
        thread-num: 10
        sniff: false
