server:
  port: 8891

spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5   #初始化时建立物理连接的个数
      min-idle: 5    # 最小连接池数量
      max-active: 20   #最大存活的连接池数量
      max-wait: 60000   #获取连接时最大等待时间
      time-between-eviction-runs-millis: 60000    #指定空闲连接检查、废弃连接清理、空闲连接池大小调整之间的操作时间间隔
      min-evictable-idle-time-millis: 300000    #连接保持空闲而不被驱逐的最长时间
      validation-query: select 1 from dual    #检测连接是否有效的SQL
      test-while-idle: true   # testWhileIdle的作用跟testOnBorrow是差不多的，都是在获取连接的时候测试连接的有效性，如果两者都为true，则testOnBorrow优先级高，则不会使用到testWhileIdle
      test-on-borrow: false   #如果为true（默认false），当应用向连接池申请连接时，连接池会判断这条连接是否是可用的
      test-on-return: false   #如果为true（默认false），当应用使用完连接，连接池回收连接的时候会判断该连接是否还可用
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        login-username: admin
        login-password: admin
        enabled: true

# Mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.daishuai.distribute.entity

# 日志级别
logging:
  level:
    com:
      daishuai:
        distribute:
          dao: debug
